#!/usr/bin/env python3
"""
Gerber to G-code converter for PCB milling
Converts Gerber files to GRBL-compatible G-code for CNC milling
"""

import argparse
import sys
import os
from pathlib import Path
from typing import List, Tuple
import re

try:
    from pygerber.gerberx3.api.v2 import (
        GerberFile,
        FileTypeEnum,
        ImageFormatEnum,
        PixelFormatEnum,
    )
except ImportError:
    print("Error: pygerber library not found. Install with: pip install pygerber")
    sys.exit(1)

try:
    import numpy as np
    from PIL import Image
except ImportError:
    print("Error: Required libraries not found. Install with: pip install numpy pillow")
    sys.exit(1)


class GerberToGcode:
    def __init__(self, args):
        self.input_file = args.input
        self.output_file = args.output
        self.tool_diameter = args.tool_diameter
        self.feed_rate = args.feed_rate
        self.plunge_rate = args.plunge_rate
        self.cut_depth = args.cut_depth
        self.safe_height = args.safe_height
        self.spindle_speed = args.spindle_speed
        self.isolation_passes = args.isolation_passes
        self.isolation_step = args.isolation_step
        self.dpi = args.dpi
        self.invert = args.invert
        
    def generate_gcode_header(self) -> str:
        """Generate G-code header with initialization commands"""
        header = [
            "; G-code generated by Gerber to G-code converter",
            f"; Input file: {self.input_file}",
            f"; Tool diameter: {self.tool_diameter} mm",
            f"; Feed rate: {self.feed_rate} mm/min",
            f"; Cut depth: {self.cut_depth} mm",
            "",
            "G21         ; Set units to millimeters",
            "G90         ; Absolute positioning",
            "G94         ; Feed rate per minute",
            f"M3 S{self.spindle_speed}  ; Start spindle",
            "G4 P2       ; Dwell 2 seconds for spindle to reach speed",
            f"G0 Z{self.safe_height}    ; Move to safe height",
            ""
        ]
        return "\n".join(header)
    
    def generate_gcode_footer(self) -> str:
        """Generate G-code footer with shutdown commands"""
        footer = [
            "",
            f"G0 Z{self.safe_height}    ; Move to safe height",
            "M5          ; Stop spindle",
            "G0 X0 Y0    ; Return to origin",
            "M2          ; Program end",
            ""
        ]
        return "\n".join(footer)
    
    def render_gerber_to_bitmap(self) -> np.ndarray:
        """Render Gerber file to a bitmap image using pygerber"""
        from io import BytesIO

        try:
            # Load the Gerber file
            gerber_file = GerberFile.from_file(
                self.input_file,
                file_type=FileTypeEnum.INFER_FROM_EXTENSION
            )

            # Parse the Gerber file
            parsed_file = gerber_file.parse()

            # Render to raster image in memory
            # Convert DPI to DPMM (dots per millimeter): dpmm = dpi / 25.4
            dpmm = int(self.dpi / 25.4)
            buffer = BytesIO()
            parsed_file.render_raster(
                destination=buffer,
                dpmm=dpmm,
                pixel_format=PixelFormatEnum.RGBA,
                image_format=ImageFormatEnum.PNG,
            )

            # Load the image from the buffer
            buffer.seek(0)
            pil_image = Image.open(buffer)

            # Convert to grayscale then to numpy array
            pil_image = pil_image.convert('L')
            img_array = np.array(pil_image)

            # Invert if needed (for isolation routing)
            if self.invert:
                img_array = 255 - img_array

            return img_array

        except Exception as e:
            print(f"Error rendering Gerber file: {e}")
            import traceback
            traceback.print_exc()
            sys.exit(1)
    
    def smooth_path(self, path: np.ndarray, tolerance: float = 0.5) -> np.ndarray:
        """Smooth a path using Douglas-Peucker algorithm"""
        from skimage.measure import approximate_polygon
        if len(path) < 3:
            return path
        return approximate_polygon(path, tolerance=tolerance)

    def bitmap_to_toolpaths(self, bitmap: np.ndarray) -> List[List[Tuple[float, float]]]:
        """Convert bitmap to toolpaths using contour detection"""
        from skimage import measure, morphology

        # Threshold the image using a slightly lower threshold for better sensitivity
        val_min, val_max = bitmap.min(), bitmap.max()
        threshold = val_min + (val_max - val_min) * 0.4  # Lower threshold = more sensitive
        binary = bitmap > threshold

        # Add padding around the image to prevent border contours from being cut off
        pad_size = 2
        binary = np.pad(binary, pad_size, mode='constant', constant_values=False)

        # Morphological operations to improve edge detection
        # Close small gaps in the binary image
        binary = morphology.closing(binary, morphology.disk(1))
        # Remove small noise
        binary = morphology.remove_small_objects(binary, max_size=10)
        binary = morphology.remove_small_holes(binary, max_size=10)

        # Find contours using marching squares algorithm
        contours = measure.find_contours(binary.astype(float), 0.5)

        # Adjust contour coordinates to account for padding
        contours = [contour - pad_size for contour in contours]

        # Convert pixel coordinates to mm
        scale_factor = 25.4 / self.dpi

        # Smoothing tolerance in pixels (adjust based on DPI)
        smooth_tolerance = max(0.5, self.dpi / 2000)

        paths = []
        for contour in contours:
            # Smooth the contour to reduce choppiness at turns
            smoothed = self.smooth_path(contour, tolerance=smooth_tolerance)

            # Convert to (x, y) in mm - note: row=Y, col=X
            path = [(point[1] * scale_factor, point[0] * scale_factor)
                    for point in smoothed]
            if len(path) >= 2:
                paths.append(path)

        print(f"Found {len(paths)} contours")
        return paths
    
    def toolpaths_to_gcode(self, paths: List[List[Tuple[float, float]]]) -> List[str]:
        """Convert toolpaths to G-code commands"""
        gcode_lines = []
        
        for pass_num in range(self.isolation_passes):
            offset = pass_num * self.isolation_step
            
            gcode_lines.append(f"; Isolation pass {pass_num + 1}")
            
            for path in paths:
                if len(path) == 0:
                    continue
                
                # Move to start of path at safe height
                x, y = path[0]
                x += offset
                gcode_lines.append(f"G0 X{x:.4f} Y{y:.4f} Z{self.safe_height}")
                
                # Plunge to cutting depth
                gcode_lines.append(f"G1 Z{-self.cut_depth:.4f} F{self.plunge_rate}")
                
                # Cut along path
                for x, y in path[1:]:
                    x += offset
                    gcode_lines.append(f"G1 X{x:.4f} Y{y:.4f} F{self.feed_rate}")
                
                # Retract to safe height
                gcode_lines.append(f"G0 Z{self.safe_height}")
            
            gcode_lines.append("")
        
        return gcode_lines
    
    def convert(self):
        """Main conversion process"""
        print(f"Converting {self.input_file} to G-code...")
        print(f"Tool diameter: {self.tool_diameter} mm")
        print(f"Feed rate: {self.feed_rate} mm/min")
        print(f"Cut depth: {self.cut_depth} mm")
        
        # Render Gerber to bitmap
        print("Rendering Gerber file...")
        bitmap = self.render_gerber_to_bitmap()
        
        # Convert bitmap to toolpaths
        print("Generating toolpaths...")
        paths = self.bitmap_to_toolpaths(bitmap)
        
        # Generate G-code
        print("Generating G-code...")
        gcode = []
        gcode.append(self.generate_gcode_header())
        gcode.extend(self.toolpaths_to_gcode(paths))
        gcode.append(self.generate_gcode_footer())
        
        # Write to file
        with open(self.output_file, 'w') as f:
            f.write('\n'.join(gcode))
        
        print(f"G-code written to {self.output_file}")
        print(f"Total lines: {len(gcode)}")


def main():
    parser = argparse.ArgumentParser(
        description='Convert Gerber files to GRBL G-code for PCB milling',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    
    # Input/Output
    parser.add_argument('input', help='Input Gerber file (.gbr, .gtl, .gbl, etc.)')
    parser.add_argument('-o', '--output', help='Output G-code file', default='output.nc')
    
    # Tool settings
    parser.add_argument('-d', '--tool-diameter', type=float, default=0.1,
                       help='Tool diameter in mm')
    
    # Feed rates
    parser.add_argument('-f', '--feed-rate', type=int, default=200,
                       help='Cutting feed rate in mm/min')
    parser.add_argument('-p', '--plunge-rate', type=int, default=50,
                       help='Plunge feed rate in mm/min')
    
    # Cut parameters
    parser.add_argument('-c', '--cut-depth', type=float, default=0.1,
                       help='Depth of cut in mm (positive value)')
    parser.add_argument('-z', '--safe-height', type=float, default=2.0,
                       help='Safe Z height for rapid moves in mm')
    
    # Spindle
    parser.add_argument('-s', '--spindle-speed', type=int, default=10000,
                       help='Spindle speed in RPM')
    
    # Isolation routing
    parser.add_argument('-i', '--isolation-passes', type=int, default=1,
                       help='Number of isolation passes')
    parser.add_argument('--isolation-step', type=float, default=0.1,
                       help='Step over between isolation passes in mm')
    
    # Rendering
    parser.add_argument('--dpi', type=int, default=1000,
                       help='DPI for Gerber rendering')
    parser.add_argument('--invert', action='store_true',
                       help='Invert the Gerber image (for isolation routing)')
    
    args = parser.parse_args()
    
    # Validate input file
    if not os.path.exists(args.input):
        print(f"Error: Input file '{args.input}' not found")
        sys.exit(1)
    
    # Create converter and run
    converter = GerberToGcode(args)
    converter.convert()


if __name__ == '__main__':
    main()
